# Changes here will be overwritten by Copier
SelectCitation:
- AddCitationFile_flag
- AddCFFConvert_flag
SelectCodeQualityFeatures:
- AddLocalTests_flag
- SelectGitHubActions_flag
- AddLinting_flag
SelectCommunityFeatures: []
SelectDocumentationFeatures:
- AddLocalDocumentation_flag
- AddOnlineDocumentation_flag
- AddGitHubActionDocumentation_flag
SelectGitHubActions:
- AddGitHubActionBuild_flag
- AddLinkCheck_flag
SelectPublishReleaseFeatures:
- SelectCitation_flag
- AddZenodo_flag
_commit: 0.6.1
_src_path: https://github.com/nlesc/python-template.git
copyright_holder: Alraune Zech
email: a.zech@uu.nl
full_name: Alraune Zech
github_organization: AlrauneZ
keywords: subsurface transport, dispersion, macrodispersivity
license: Apachev2
package_name: macrodispersivity
package_short_description: Macrodispersivity
template_profile: recommended
version: 0.1.0
